import memeber1Image from "../assets/TeamMember1.png";
import memeber2Image from "../assets/TeamMember2.png";

import influencerImage1 from "../assets/InfluencerReviewImage.png";
import influencerImage2 from "../assets/InfluencerReviewImage2.png";

import brandCardImage1 from "../assets/BrandCardImage1.jpg";
import brandCardImage2 from "../assets/BrandCardImage2.jpg";

import brandIconImage from "../assets/BrandIconImage.png";

import followersCardImage from "../assets/BrandCardImage1.jpg";

export const influencersList = [
  {
    id: 1,
    facebookLink: "#",
    instagranLink: "#",
    youtubeLink: "#",
    image: memeber1Image,
  },
  {
    id: 2,
    facebookLink: "#",
    instagranLink: "#",
    youtubeLink: "#",
    image: memeber2Image,
  },
  {
    id: 3,
    facebookLink: "#",
    instagranLink: "#",
    youtubeLink: "#",
    image: memeber1Image,
  },
  {
    id: 4,
    facebookLink: "#",
    instagranLink: "#",
    youtubeLink: "#",
    image: memeber2Image,
  },
  {
    id: 5,
    facebookLink: "#",
    instagranLink: "#",
    youtubeLink: "#",
    image: memeber1Image,
  },
  {
    id: 6,
    facebookLink: "#",
    instagranLink: "#",
    youtubeLink: "#",
    image: memeber2Image,
  },
];

export const brandList = [
  {
    id: 1,
    socialIconLink: "",
    name: "Huda Saud",
    userName: "@hudasaud",
    facebookFollowers: "330",
    instagramFollowers: "440",
    youtubeFollowers: "550",
    youtubeLink: "#",
    image: memeber1Image,
  },
  {
    id: 2,
    socialIconLink: "",
    name: "Huda Saud",
    userName: "@hudasaud",
    facebookFollowers: "330",
    instagramFollowers: "440",
    youtubeFollowers: "550",
    image: memeber2Image,
  },
  {
    id: 3,
    socialIconLink: "",
    name: "Huda Saud",
    userName: "@hudasaud",
    facebookFollowers: "330",
    instagramFollowers: "440",
    youtubeFollowers: "550",
    image: memeber1Image,
  },
  {
    id: 4,
    socialIconLink: "",
    name: "Huda Saud",
    userName: "@hudasaud",
    facebookFollowers: "330",
    instagramFollowers: "440",
    youtubeFollowers: "550",
    image: memeber2Image,
  },
  {
    id: 5,
    socialIconLink: "",
    name: "Huda Saud",
    userName: "@hudasaud",
    facebookFollowers: "330",
    instagramFollowers: "440",
    youtubeFollowers: "550",
    image: memeber1Image,
  },
  {
    id: 6,
    socialIconLink: "",
    name: "Huda Saud",
    userName: "@hudasaud",
    facebookFollowers: "330",
    instagramFollowers: "440",
    youtubeFollowers: "550",
    image: memeber2Image,
  },
  {
    id: 7,
    socialIconLink: "",
    name: "Huda Saud",
    userName: "@hudasaud",
    facebookFollowers: "330",
    instagramFollowers: "440",
    youtubeFollowers: "550",
    image: memeber1Image,
  },
  {
    id: 8,
    socialIconLink: "",
    name: "Huda Saud",
    userName: "@hudasaud",
    facebookFollowers: "330",
    instagramFollowers: "440",
    youtubeFollowers: "550",
    image: memeber2Image,
  },
  {
    id: 9,
    socialIconLink: "",
    name: "Huda Saud",
    userName: "@hudasaud",
    facebookFollowers: "330",
    instagramFollowers: "440",
    youtubeFollowers: "550",
    image: memeber1Image,
  },
  {
    id: 10,
    socialIconLink: "",
    name: "Huda Saud",
    userName: "@hudasaud",
    facebookFollowers: "330",
    instagramFollowers: "440",
    youtubeFollowers: "550",
    image: memeber2Image,
  },
];

export const influencerReviewList = [
  {
    id: 1,
    image: influencerImage1,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    followers: "2.3M",
    genre: "Comedy",
    channelName: "TIKTOK.COM/@LUKEVERNON_",
  },
  {
    id: 2,
    image: influencerImage2,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    followers: "2.3M",
    genre: "Comedy",
    channelName: "TIKTOK.COM/@LUKEVERNON_",
  },
  {
    id: 3,
    image: influencerImage1,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    followers: "2.3M",
    genre: "Comedy",
    channelName: "TIKTOK.COM/@LUKEVERNON_",
  },
  {
    id: 4,
    image: influencerImage2,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    followers: "2.3M",
    genre: "Comedy",
    channelName: "TIKTOK.COM/@LUKEVERNON_",
  },
  {
    id: 5,
    image: influencerImage1,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    followers: "2.3M",
    genre: "Comedy",
    channelName: "TIKTOK.COM/@LUKEVERNON_",
  },
  {
    id: 6,
    image: influencerImage2,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    followers: "2.3M",
    genre: "Comedy",
    channelName: "TIKTOK.COM/@LUKEVERNON_",
  },
  {
    id: 7,
    image: influencerImage1,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    followers: "2.3M",
    genre: "Comedy",
    channelName: "TIKTOK.COM/@LUKEVERNON_",
  },
  {
    id: 8,
    image: influencerImage2,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    followers: "2.3M",
    genre: "Comedy",
    channelName: "TIKTOK.COM/@LUKEVERNON_",
  },
  {
    id: 9,
    image: influencerImage1,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    followers: "2.3M",
    genre: "Comedy",
    channelName: "TIKTOK.COM/@LUKEVERNON_",
  },
  {
    id: 10,
    image: influencerImage2,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    followers: "2.3M",
    genre: "Comedy",
    channelName: "TIKTOK.COM/@LUKEVERNON_",
  },
];

export const brandReviewList = [
  {
    id: 1,
    image: influencerImage1,
    rating: 3,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    position: "Senior Research Manager",
  },
  {
    id: 2,
    image: influencerImage2,
    rating: 3,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    position: "Senior Research Manager",
  },
  {
    id: 3,
    image: influencerImage1,
    rating: 5,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    position: "Senior Research Manager",
  },
  {
    id: 4,
    image: influencerImage2,
    rating: 4,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    position: "Senior Research Manager",
  },
  {
    id: 5,
    image: influencerImage1,
    rating: 3,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    position: "Senior Research Manager",
  },
  {
    id: 6,
    image: influencerImage2,
    rating: 2,
    review:
      "Lorem ipsum dolor sit amet consectetur. Consequat auctor consectetur nunc vitae dolor blandit. Elit enim massa etiam neque laoreet lorem sed. ",
    name: "Anthony Bahringer",
    position: "Senior Research Manager",
  },
];

export const brandCardList = [
  {
    id: 1,
    image: brandCardImage1,
    brandIconImage: brandIconImage,
    brandName: "Adidas",
    brandFacebookLink: "",
    brandInstagramLink: "",
    brandYoutubeLink: "",
    title: "Tech4Good: Harnessing Technology for Positive Impact",
    location: "Jordan",
    itemArray: ["clothing", "clothing", "clothing"],
    fromDate: "11/05/2022",
    toDate: "22/05/2022",
    days: 10,
  },
  {
    id: 2,
    image: brandCardImage2,
    brandIconImage: brandIconImage,
    brandName: "Adidas",
    brandFacebookLink: "",
    brandInstagramLink: "",
    brandYoutubeLink: "",
    title: "Tech4Good: Harnessing Technology for Positive Impact",
    location: "Jordan",
    itemArray: ["clothing", "clothing", "clothing", "clothing", "clothing"],
    fromDate: "11/05/2022",
    toDate: "22/05/2022",
    days: 10,
  },
  {
    id: 3,
    image: brandCardImage1,
    brandIconImage: brandIconImage,
    brandName: "Adidas",
    brandFacebookLink: "",
    brandInstagramLink: "",
    brandYoutubeLink: "",
    title: "Tech4Good: Harnessing Technology for Positive Impact",
    location: "Jordan",
    itemArray: ["clothing", "clothing", "clothing", "clothing"],
    fromDate: "11/05/2022",
    toDate: "22/05/2022",
    days: 10,
  },
  {
    id: 4,
    image: brandCardImage2,
    brandIconImage: brandIconImage,
    brandName: "Adidas",
    brandFacebookLink: "",
    brandInstagramLink: "",
    brandYoutubeLink: "",
    title: "Tech4Good: Harnessing Technology for Positive Impact",
    location: "Jordan",
    itemArray: ["clothing", "clothing", "clothing"],
    fromDate: "11/05/2022",
    toDate: "22/05/2022",
    days: 10,
  },
  {
    id: 5,
    image: brandCardImage1,
    brandIconImage: brandIconImage,
    brandName: "Adidas",
    brandFacebookLink: "",
    brandInstagramLink: "",
    brandYoutubeLink: "",
    title: "Tech4Good: Harnessing Technology for Positive Impact",
    location: "Jordan",
    itemArray: ["clothing", "clothing"],
    fromDate: "11/05/2022",
    toDate: "22/05/2022",
    days: 10,
  },
  {
    id: 6,
    image: brandCardImage2,
    brandIconImage: brandIconImage,
    brandName: "Adidas",
    brandFacebookLink: "",
    brandInstagramLink: "",
    brandYoutubeLink: "",
    title: "Tech4Good: Harnessing Technology for Positive Impact",
    location: "Jordan",
    itemArray: [
      "clothing",
      "clothing",
      "clothing",
      "clothing",
      "clothing",
      "clothing",
      "clothing",
      "clothing",
      "clothing",
      "clothing",
    ],
    fromDate: "11/05/2022",
    toDate: "22/05/2022",
    days: 10,
  },
  {
    id: 7,
    image: brandCardImage1,
    brandIconImage: brandIconImage,
    brandName: "Adidas",
    brandFacebookLink: "",
    brandInstagramLink: "",
    brandYoutubeLink: "",
    title: "Tech4Good: Harnessing Technology for Positive Impact",
    location: "Jordan",
    itemArray: ["clothing", "clothing"],
    fromDate: "11/05/2022",
    toDate: "22/05/2022",
    days: 10,
  },
  {
    id: 8,
    image: brandCardImage2,
    brandIconImage: brandIconImage,
    brandName: "Adidas",
    brandFacebookLink: "",
    brandInstagramLink: "",
    brandYoutubeLink: "",
    title: "Tech4Good: Harnessing Technology for Positive Impact",
    location: "Jordan",
    itemArray: ["clothing", "clothing"],
    fromDate: "11/05/2022",
    toDate: "22/05/2022",
    days: 10,
  },
];

export const followersCard = [
  {
    id: 1,
    image: followersCardImage,
    name: "Huda Saud",
    instaLink: "",
    facebookLink: "",
    youtubeLink: "",
    followers: 5,
  },
  {
    id: 2,
    image: followersCardImage,
    name: "Huda Saud",
    instaLink: "",
    facebookLink: "",
    youtubeLink: "",
    followers: 5,
  },
  {
    id: 3,
    image: followersCardImage,
    name: "Huda Saud",
    instaLink: "",
    facebookLink: "",
    youtubeLink: "",
    followers: 5,
  },
  {
    id: 4,
    image: followersCardImage,
    name: "Huda Saud",
    instaLink: "",
    facebookLink: "",
    youtubeLink: "",
    followers: 5,
  },
  {
    id: 5,
    image: followersCardImage,
    name: "Huda Saud",
    instaLink: "",
    facebookLink: "",
    youtubeLink: "",
    followers: 5,
  },
  {
    id: 6,
    image: followersCardImage,
    name: "Huda Saud",
    instaLink: "",
    facebookLink: "",
    youtubeLink: "",
    followers: 5,
  },
  {
    id: 7,
    image: followersCardImage,
    name: "Huda Saud",
    instaLink: "",
    facebookLink: "",
    youtubeLink: "",
    followers: 5,
  },
  {
    id: 8,
    image: followersCardImage,
    name: "Huda Saud",
    instaLink: "",
    facebookLink: "",
    youtubeLink: "",
    followers: 5,
  },
  {
    id: 9,
    image: followersCardImage,
    name: "Huda Saud",
    instaLink: "",
    facebookLink: "",
    youtubeLink: "",
    followers: 5,
  },
  {
    id: 10,
    image: followersCardImage,
    name: "Huda Saud",
    instaLink: "",
    facebookLink: "",
    youtubeLink: "",
    followers: 5,
  },
];

export const faqData = [
  {
    question: "What is Lorem Ipsum?",
    answer:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    question: "Why do we use it?",
    answer:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
  },
  {
    question: "Where does it come from?",
    answer:
      "Contrary to popular belief, Lorem Ipsum is not simply random text.",
  },
  {
    question: "Is it safe to use Lorem Ipsum?",
    answer: "Yes, Lorem Ipsum is safe to use and has been the industry's...",
  },
  {
    question: "How can I get started?",
    answer: "You can get started by following the provided documentation.",
  },
];
